/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CASOSDEUSO;

import MODELO.Cliente;
import java.time.LocalDate;


/**
 *
 * @author Lenovo
 */
public class Ventana_Registro_Cliente extends javax.swing.JPanel {

    /**
     * Creates new form Ventana_Registro_Cliente
     */
    public Ventana_Registro_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_apellido = new javax.swing.JTextField();
        campo_dni = new javax.swing.JTextField();
        campo_fecha_nacimiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_correo = new javax.swing.JTextField();
        campo_telefono = new javax.swing.JTextField();
        campo_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_nombre_usuario = new javax.swing.JTextField();
        campo_contraseña = new javax.swing.JTextField();
        campo_confirmacion_contraseña = new javax.swing.JTextField();
        CrearCliente = new javax.swing.JButton();

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("INGRESE SU NOMBRE");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("INGRESE SUS DATOS PERSONALES");

        jLabel5.setText("INGRESE SUS DATOS DE CONTACTO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("REGISTRE SU NUEVA CUENTA");

        campo_nombre.setForeground(new java.awt.Color(204, 204, 204));
        campo_nombre.setText("NOMBRE");
        campo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombreActionPerformed(evt);
            }
        });

        campo_apellido.setForeground(new java.awt.Color(204, 204, 204));
        campo_apellido.setText("APELLIDO");
        campo_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_apellidoActionPerformed(evt);
            }
        });

        campo_dni.setForeground(new java.awt.Color(204, 204, 204));
        campo_dni.setText("INGRESE SU DNI");
        campo_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_dniActionPerformed(evt);
            }
        });

        campo_fecha_nacimiento.setForeground(new java.awt.Color(204, 204, 204));
        campo_fecha_nacimiento.setText("FECHA DE NACIMIENTO");
        campo_fecha_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_fecha_nacimientoActionPerformed(evt);
            }
        });

        jLabel2.setText("INGRESE SUS DATOS PERSONALES");

        jLabel4.setText("INGRESE SUS DATOS DE CONTACTO");

        campo_correo.setForeground(new java.awt.Color(204, 204, 204));
        campo_correo.setText("CORREO");
        campo_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_correoActionPerformed(evt);
            }
        });

        campo_telefono.setForeground(new java.awt.Color(204, 204, 204));
        campo_telefono.setText("TELÉFONO");
        campo_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_telefonoActionPerformed(evt);
            }
        });

        campo_direccion.setForeground(new java.awt.Color(204, 204, 204));
        campo_direccion.setText("INGRESE SU DIRECCIÓN");
        campo_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_direccionActionPerformed(evt);
            }
        });

        jLabel6.setText("INGRESE LOS DATOS DE SU CUENTA");

        campo_nombre_usuario.setForeground(new java.awt.Color(204, 204, 204));
        campo_nombre_usuario.setText("NOMBRE DE USUARIO");
        campo_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombre_usuarioActionPerformed(evt);
            }
        });

        campo_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        campo_contraseña.setText("CONTRASEÑA");
        campo_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_contraseñaActionPerformed(evt);
            }
        });

        campo_confirmacion_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        campo_confirmacion_contraseña.setText("CONFIRME SU CONTRASEÑA");
        campo_confirmacion_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_confirmacion_contraseñaActionPerformed(evt);
            }
        });

        CrearCliente.setText("CREAR CUENTA");
        CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_confirmacion_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campo_nombre_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(campo_contraseña, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campo_correo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campo_telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)))))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_nombre)
                    .addComponent(campo_apellido)
                    .addComponent(campo_dni)
                    .addComponent(campo_fecha_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(campo_direccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(CrearCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(campo_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_confirmacion_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearCliente)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombreActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void campo_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_apellidoActionPerformed

    private void campo_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_dniActionPerformed
        
    }//GEN-LAST:event_campo_dniActionPerformed

    private void campo_fecha_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_fecha_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_fecha_nacimientoActionPerformed

    private void campo_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_correoActionPerformed

    private void campo_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_telefonoActionPerformed

    private void campo_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_direccionActionPerformed

    private void campo_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombre_usuarioActionPerformed

    private void campo_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_contraseñaActionPerformed

    private void campo_confirmacion_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_confirmacion_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_confirmacion_contraseñaActionPerformed

    private void CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseClicked
        
        long dni,telefono;
        String nombre,apellido,correo,direccion,fecha,nombre_usuario,contraseña,confirm_contra;
        LocalDate fecha_nacimiento;
        dni = Long.parseLong(campo_dni.getText());
        nombre = campo_nombre.getText();
        apellido = campo_apellido.getText();
        telefono = Long.parseLong(campo_telefono.getText());
        correo = campo_correo.getText();
        direccion = campo_direccion.getText();
        fecha = campo_fecha_nacimiento.getText();
        fecha_nacimiento = LocalDate.parse(fecha);
        nombre_usuario = campo_nombre_usuario.getText();
        contraseña = campo_contraseña.getText();
        confirm_contra = campo_confirmacion_contraseña.getText();
        if(contraseña.equals(confirm_contra)){
            Cliente nuevo_cliente = new Cliente(dni,nombre,apellido,telefono,correo,direccion,fecha_nacimiento,nombre_usuario,contraseña);
        }
    }//GEN-LAST:event_CrearClienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearCliente;
    private javax.swing.JTextField campo_apellido;
    private javax.swing.JTextField campo_confirmacion_contraseña;
    private javax.swing.JTextField campo_contraseña;
    private javax.swing.JTextField campo_correo;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_dni;
    private javax.swing.JTextField campo_fecha_nacimiento;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_nombre_usuario;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
